name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"] # Define the Python versions to test against
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run Tests
        run: pytest --benchmark-disable tests/
      # - name: Run Type Checking (pytype)
        # run: pytype
      - name: Run Linter (flake8)
        run: flake8 src/
      - name: Run Formatter Check (black)
        run: black --check src/
